name: Lighthouse Check
on:
  schedule:
    - cron: "0 0/6 * * *"

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  URL_TO_CHECK: "https://react-tailwind-vercel-starter.vercel.app"
  HTML_FILE_NAME: "lighthouse-report.html"

jobs:
  call-lighthouse-workflow:
    uses: mikesprague/reusable-workflows/.github/workflows/lighthouse.yml@main
    secrets:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN}}
    with:
      url: https://react-tailwind-vercel-starter.vercel.app

